version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=financeiro
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: financeiro
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
    mysql_data:
