version: '3.8'

services:
  # Serviço da sua aplicação
  app:
    build: .
    volumes:
      # Use o volume para mapear o .war diretamente do seu projeto para o container
      # Isso facilita o desenvolvimento, pois você não precisa reconstruir a imagem toda hora.
      # Remova ou comente essa linha se quiser que o Dockerfile copie o .war de forma definitiva
      - ./target/financeiro-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/app.war
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # Variáveis de ambiente para a sua aplicação
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}

  # Serviço do banco de dados PostgreSQL
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data: