version: '3.8'

services:
  # Serviço da sua aplicação
  app:
    build: .
    volumes:
      # Use o volume para mapear o .war diretamente do seu projeto para o container
      # Isso facilita o desenvolvimento, pois você não precisa reconstruir a imagem toda hora.
      # Remova ou comente essa linha se quiser que o Dockerfile copie o .war de forma definitiva
      - ./target/finopen.war:/usr/local/tomcat/webapps/app.war
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # Variáveis de ambiente para a sua aplicação
      - DATABASE_HOST=db
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_NAME=creditoSeguro
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

  # Serviço do banco de dados PostgreSQL
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      
      - POSTGRES_DB=creditoSeguro
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data: