version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
  assis:
    image: oscarfonts/h2
    container_name: h2-database
    ports:
      - "8082:8082"
    volumes:
      - h2-data:/opt/h2-data
    environment:
      - H2_OPTIONS=-tcp -tclAllowOthers -web -webAllowOthers
volumes:
    h2-data:
